# Generated by Django 3.0.7 on 2020-06-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdefaultaddress',
            name='default',
            field=models.BooleanField(default=True),
        ),
    ]
