# Generated by Django 3.0.7 on 2020-06-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200612_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.URLField(max_length=2083),
        ),
    ]
